<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>2eab2b07-4394-4e89-b3af-2a71f8346343</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Supabase" Version="1.6.0" />
    </ItemGroup>

</Project>
